name: Build and publish latest package

on:
  workflow_dispatch:
  push:
    branches:
      - feature/buildjob
    
jobs:
  build:
    name: "Build"
    runs-on: [linux, X64]

    steps:
    - name: checkout
      uses: actions/checkout@v2     
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.2